remote_theme: pages-themes/modernist@v0.2.0
# https://github.com/pages-themes/modernist.git
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: DavidPRush's homepage
description: Bookmark this to keep an eye on my project updates!
show_downloads: false